import { Mina } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const mina = Mina({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mina.className}  antialiased`}>
        <div className="min-h-screen">
          {/* Navigation */}
          <Navbar />

          {/* Main Content Area */}
          <main className="w-full mx-auto bg-gray-950 text-slate-200">
            {children}
          </main>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
